image: docker:18.04.0-ce-dind

before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin

build-job:
  tags:
    - docker
  script:
    - docker build -t "$CI_REGISTRY/$CI_PROJECT_NAME" .
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAME"
